services:
  primary:
    container_name: primary
    build:
      context: ./primary
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./primary/data:/var/lib/postgresql/data
    networks:
      - pg_net

  standby:
    container_name: standby
    build:
      context: ./standby
    restart: unless-stopped
    ports:
      - "5433:5432"
    depends_on:
      - primary
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./standby/data:/var/lib/postgresql/data
    networks:
      - pg_net
  pgpool:
    container_name: pgpool
    build:
      context: ./pgpool
    ports:
      - "9999:9999" # Порт, который будет слушать Pgpool
      - "9898:9898"
    environment:
      - PGPOOL_PARAMS_BACKEND_HOSTNAME0=primary
      - PGPOOL_PARAMS_BACKEND_PORT0=5432
      - PGPOOL_PARAMS_BACKEND_WEIGHT0=1
      - PGPOOL_PARAMS_BACKEND_FLAG0=ALWAYS_PRIMARY|ALLOW_TO_FAILOVER
      
      - PGPOOL_PARAMS_BACKEND_HOSTNAME1=standby
      - PGPOOL_PARAMS_BACKEND_PORT1=5432
      - PGPOOL_PARAMS_BACKEND_WEIGHT1=1
      - PGPOOL_PARAMS_BACKEND_FLAG1=ALLOW_TO_FAILOVER
      
      # === РЕЖИМ КЛАСТЕРИЗАЦИИ ===
      - PGPOOL_PARAMS_BACKEND_CLUSTERING_MODE=streaming_replication
      
      # === БАЛАНСИРОВКА НАГРУЗКИ ===
      - PGPOOL_PARAMS_LOAD_BALANCE_MODE=on
      - PGPOOL_PARAMS_DISABLE_LOAD_BALANCE_ON_WRITE=transaction
      
      # === HEALTH CHECK ===
      - PGPOOL_PARAMS_HEALTH_CHECK_PERIOD=5
      - PGPOOL_PARAMS_HEALTH_CHECK_TIMEOUT=20
      - PGPOOL_PARAMS_HEALTH_CHECK_USER=postgres
      - PGPOOL_PARAMS_HEALTH_CHECK_PASSWORD=postgres
      - PGPOOL_PARAMS_HEALTH_CHECK_MAX_RETRIES=3
      
      # === АУТЕНТИФИКАЦИЯ ===
      - PGPOOL_PARAMS_SR_CHECK_USER=postgres
      - PGPOOL_PARAMS_SR_CHECK_PASSWORD=postgres
      - PGPOOL_PARAMS_AUTHENTICATION_TIMEOUT=60
      - PGPOOL_PARAMS_NUM_INIT_CHILDREN=32
      - PGPOOL_PARAMS_MAX_POOL=4
      
      # === FAILOVER: путь внутри образа + плейсхолдеры Pgpool-II 4.x (%H/%r = хост/порт нового main)
      - PGPOOL_PARAMS_FAILOVER_COMMAND=/usr/local/bin/pgpool-scripts/failover.sh %d %H %r %m
      
      # === ЛОГИРОВАНИЕ ===
      - PGPOOL_PARAMS_LOG_CONNECTIONS=on
      - PGPOOL_PARAMS_LOG_DISCONNECTIONS=on
      - PGPOOL_PARAMS_LOG_HOSTNAME=on
      
      # === ОСНОВНЫЕ НАСТРОЙКИ ===
      - PGPOOL_PARAMS_LISTEN_ADDRESSES=*
      - PGPOOL_PARAMS_PORT=9999
      - PGPOOL_PARAMS_ENABLE_POOL_HBA=off
      
      # === ДОПОЛНИТЕЛЬНО: пользователи для pool_passwd ===
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - primary
      - standby
    networks:
      - pg_net # Та же сеть, что и у primary/standby

networks:
  pg_net:
    driver: bridge