services:
  primary:
    container_name: primary
    build:
      context: ./primary
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./primary/data:/var/lib/postgresql/data
    networks:
      - pg_net

  standby:
    container_name: standby
    build:
      context: ./standby
    restart: unless-stopped
    ports:
      - "5433:5432"
    depends_on:
      - primary
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./standby/data:/var/lib/postgresql/data
    networks:
      - pg_net
  pgpool:
    container_name: pgpool
    build:
      context: ./pgpool
    ports:
      - "9999:9999" # Порт, который будет слушать Pgpool
    environment:
      # --- Важные параметры для подключения к БД ---
      - PGPOOL_BACKEND_NODES=0:primary:5432,1:standby:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpass
      # --- Параметры Pgpool ---
      - PGPOOL_CONFIG_FILE=/etc/pgpool2/pgpool.conf
      - PGPOOL_PCP_TIMEOUT=10
    depends_on:
      - primary
      - standby
    networks:
      - pg_net # Та же сеть, что и у primary/standby

networks:
  pg_net:
    driver: bridge